// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuBYNsAcbVpeGDQRRUGhwa6nipuH4TISc',
    appId: '1:83589908302:web:bcc5c97325caeb2c0c401f',
    messagingSenderId: '83589908302',
    projectId: 'medicine-tracker-9f7ed',
    authDomain: 'medicine-tracker-9f7ed.firebaseapp.com',
    storageBucket: 'medicine-tracker-9f7ed.firebasestorage.app',
    measurementId: 'G-YZZ2LF9C2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1unpAnSEgPnWrmhss0Pv_u6OTBtXDeNE',
    appId: '1:83589908302:android:5da38eefc27b4ab60c401f',
    messagingSenderId: '83589908302',
    projectId: 'medicine-tracker-9f7ed',
    storageBucket: 'medicine-tracker-9f7ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgQNXNLWtLKMoH9OIe5vWDKfuowQaiRHc',
    appId: '1:83589908302:ios:33c7b13d9630454f0c401f',
    messagingSenderId: '83589908302',
    projectId: 'medicine-tracker-9f7ed',
    storageBucket: 'medicine-tracker-9f7ed.firebasestorage.app',
    iosBundleId: 'com.yourname.medicineTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgQNXNLWtLKMoH9OIe5vWDKfuowQaiRHc',
    appId: '1:83589908302:ios:33c7b13d9630454f0c401f',
    messagingSenderId: '83589908302',
    projectId: 'medicine-tracker-9f7ed',
    storageBucket: 'medicine-tracker-9f7ed.firebasestorage.app',
    iosBundleId: 'com.yourname.medicineTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuBYNsAcbVpeGDQRRUGhwa6nipuH4TISc',
    appId: '1:83589908302:web:a920a3b663575db40c401f',
    messagingSenderId: '83589908302',
    projectId: 'medicine-tracker-9f7ed',
    authDomain: 'medicine-tracker-9f7ed.firebaseapp.com',
    storageBucket: 'medicine-tracker-9f7ed.firebasestorage.app',
    measurementId: 'G-7XQ7TGQCEW',
  );
}
